# Generated by Django 4.0.4 on 2022-06-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your title (e.g. School abroad)', max_length=100, verbose_name='Title')),
                ('message', models.TextField(blank=True, help_text='Write something here...', null=True, verbose_name='Message')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('likes', models.IntegerField(blank=True, default=0, help_text='Enter your number of likes (e.g. 20)', null=True, verbose_name='Likes')),
                ('dislikes', models.IntegerField(blank=True, default=0, help_text='Enter your number of dislikes (e.g. 20)', null=True, verbose_name='Dislikes')),
            ],
            options={
                'ordering': ['likes', 'title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name (e.g. John Smith)', max_length=45, verbose_name='Name')),
                ('password', models.CharField(help_text='Enter your password (e.g. fX$_g2i!)', max_length=45, verbose_name='Password')),
                ('email', models.EmailField(help_text='Enter your e-mail (e.g. johnsmith@gmail.com)', max_length=100, unique=True, verbose_name='E-mail')),
                ('age', models.IntegerField(blank=True, help_text='Enter your age (e.g. 18)', null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='man', max_length=5, verbose_name='Gender')),
                ('followers', models.IntegerField(blank=True, default=0, help_text='Enter your number of followers (e.g. 100)', null=True, verbose_name='Followers')),
                ('following', models.IntegerField(blank=True, default=0, help_text='Enter your number of followed people (e.g. 100)', null=True, verbose_name='Following')),
                ('image', models.ImageField(blank=True, help_text='Enter your image (e.g. .png, .jpg, .gif)', null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'ordering': ['followers', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your title (e.g. Sport discussing thread)', max_length=100, verbose_name='Title')),
                ('number_of_people', models.IntegerField(blank=True, default=6, help_text='Enter the maximum number of people (e.g. 30)', null=True, verbose_name='Maximum number of people')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, help_text='Write something here...', null=True, verbose_name='Description')),
                ('message_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.message')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'ordering': ['number_of_people', 'title'],
            },
        ),
    ]
